const ICONS = {
	UNDOS: [ 'fas', 'faUndo' ],
	REDOS: [ 'fas', 'faRedo' ],
	BOLD: [ 'fas', 'faBold' ],
	ITALIC: [ 'fas', 'faItalic' ],
	CODE_IN_LINE: [ 'fas', 'faCode' ],
	CODE_BLOCK: [ 'fas', 'faFileCode' ],
	STRIKETHROUGH:[ 'fas', 'faStrikethrough' ],
	UNDERLINE:[ 'fas', 'faUnderline' ],
	FONTBGCOLOR:[ 'fas', 'faPaintRoller' ],
	FONTCOLOR:[ 'fas', 'faPalette' ],
	FONTSIZE:[ 'fas', 'faFont' ],
	SUP:[ 'fas', 'faSuperscript' ],
	SUB:[ 'fas', 'faSubscript' ],
	LINK:[ 'fas', 'faLink' ],
	HEADING:[ 'fas', 'faHeading' ],
	BLOCKQUOTE:[ 'fas', 'faQuoteRight' ],
	ORDERED_LIST:[ 'fas', 'faListOl' ],
	UNORDERED_LIST:[ 'fas', 'faListUl' ],
	ALIGN_LEFT:[ 'fas', 'faAlignLeft' ],
	ALIGN_CENTER:[ 'fas', 'faAlignCenter' ],
	ALIGN_RIGHT:[ 'fas', 'faAlignRight' ],
	INDENT:[ 'fas', 'faIndent' ],
	OUTDENT:[ 'fas', 'faOutdent' ],
	TABLE:[ 'fas', 'faTable' ],
	DELETE:[ 'fas', 'faTrash' ],
	TH:[ 'fas', 'faThList' ],
	IMAGE: [ 'fas', 'faFileImage' ],
	// LETTERSPACING: 'LETTERSPACING'
};

export default ICONS;