/**
 * Map of all mark node types.
 * @type {Map}
 */
module.exports = {
	BOLD: 'BOLD',
	ITALIC: 'ITALIC',
	CODE_LINE: 'CODE_LINE',
	STRIKETHROUGH: 'STRIKETHROUGH',
	UNDERLINE: 'UNDERLINE',
	SUP: 'SUP',
	SUB: 'SUB',

	// mark styles
	FONTBGCOLOR: 'FONTBGCOLOR',
	FONTCOLOR: 'FONTCOLOR',
	FONTSIZE: 'FONTSIZE',
	LETTERSPACING: 'LETTERSPACING'
};